### ISSUE TITLE
Revisit UI

### ISSUE THREAD

**Issue by turtleman270** [turtleman270/Chess-Leaderboards#17]
Now that we have graphs, the tables might not be needed.
Or maybe they are?

**Comment by neverendingqs** [comment]
Does Highcharts have a "show table" option?

**Comment by turtleman270** [comment]
I didn't see one when I was looking.
They have a `showTable` option, but all it does is plop a table right below your graph

**Comment by neverendingqs** [comment]
Hmm might be good enough? Could it be on by default?
