### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by turtleman270** [turtleman270/Chess-Leaderboards#25]
We don't have a config file.

Things we could config:
-starting elo
-the k value (https://ratings.fide.com/calculator_rtd.phtml)
-probably other stuff too

**Comment by neverendingqs** [comment]
I think env var works best here, with dotenv support for local dev

**Comment by turtleman270** [comment]
I'm pretty sure you mentioned dotenv to me a while ago but I ignored it because I was already doing something else that worked lol

**Comment by neverendingqs** [comment]
Yep, except this time, Vue has native dotenv support :)

https://stackoverflow.com/a/52405998/2687324

**Comment by turtleman270** [comment]
Other things that could be config'd:
-amount of rounding
-language
