### ISSUE TITLE
Reduce graphs per page

### ISSUE THREAD

**Issue by turtleman270** [turtleman270/Chess-Leaderboards#31]
Right now we're showing way too many graphs on a page I think something like this would look better
![image](https://user-images.githubusercontent.com/12630061/57986322-7ec7d880-7a41-11e9-8978-9c1a4b4aa61e.png)

**Comment by neverendingqs** [comment]
Hmm I wonder if https://cristijora.github.io/vue-tabs/#/ would be useful here

**Comment by turtleman270** [comment]
That looks like exactly what I'm wanting
