### ISSUE TITLE
Bar chart discussion

### ISSUE THREAD

**Issue by neverendingqs** [turtleman270/Chess-Leaderboards#33]
Do we still want the bar chart now that we have a line graph? Or should we just switch back to a table?

E.g. https://github.com/turtleman270/Chess-Leaderboards/commit/492a3203cca572481c1b524d545fe5c265b79477#diff-f8645b6482765dba73cdc0aaf1ba3d41

**Comment by turtleman270** [comment]
I think the bar chart is nice to look at
We could make it so the table doesn't automatically show up
